name = "darts-online"
main = "src/online/server/worker.ts"
compatibility_date = "2024-11-15"

[durable_objects]
bindings = [
  { name = "ROOMS", class_name = "RoomDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["RoomDO"]

[vars]
ALLOW_ORIGINS = "http://localhost:5173,https://ton-domaine.pages.dev"
